/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Automovel;
import classes.Dados;
import classes.Utilidades;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gelson Tavares
 */
public class frmAutomovel extends javax.swing.JInternalFrame {

    private Dados clsdados;
    private int automovelatual = 0;
    private boolean cmdNovo = false;
    private DefaultTableModel Usertabe;

    public void setDados(Dados clsdados) {
        this.clsdados = clsdados;
    }

    public frmAutomovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidautomovel = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        cmbmodelo = new javax.swing.JComboBox<>();
        cmdprimero = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdseguinte = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdnovo = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdpesqusar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ctable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtobs = new javax.swing.JTextArea();
        cmddeletar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtidautomovel1 = new javax.swing.JTextField();
        txtpreco1 = new javax.swing.JTextField();
        cmbmodelo1 = new javax.swing.JComboBox<>();
        cmdprimero1 = new javax.swing.JButton();
        cmdanterior1 = new javax.swing.JButton();
        cmdseguinte1 = new javax.swing.JButton();
        cmdultimo1 = new javax.swing.JButton();
        cmdnovo1 = new javax.swing.JButton();
        cmdeditar1 = new javax.swing.JButton();
        cmdsalvar1 = new javax.swing.JButton();
        cmdcancelar1 = new javax.swing.JButton();
        cmdpesqusar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ctable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtobs1 = new javax.swing.JTextArea();
        cmddeletar1 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jTextField2.setText("jTextField2");

        jButton5.setText("jButton5");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Automovel");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Preço");

        jLabel3.setText("Obs");

        jLabel6.setText("Modelo");

        txtidautomovel.setEnabled(false);
        txtidautomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidautomovelActionPerformed(evt);
            }
        });

        txtpreco.setEnabled(false);

        cmbmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um perfil", "BMW", "MERCEDES", "TOYOTA", "ACURA", "HONDA", "SUZUKI" }));
        cmbmodelo.setEnabled(false);

        cmdprimero.setText("<<");
        cmdprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeroActionPerformed(evt);
            }
        });

        cmdanterior.setText("<");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdseguinte.setText(">");
        cmdseguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdseguinteActionPerformed(evt);
            }
        });

        cmdultimo.setText(">>");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdnovo.setText("Add");
        cmdnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovoActionPerformed(evt);
            }
        });

        cmdeditar.setText("Edt");
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });

        cmdsalvar.setText("Gdr");
        cmdsalvar.setEnabled(false);
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdcancelar.setText("cls");
        cmdcancelar.setEnabled(false);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdpesqusar.setText("psq");
        cmdpesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesqusarActionPerformed(evt);
            }
        });

        Ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ctable);

        txtobs.setColumns(20);
        txtobs.setRows(5);
        jScrollPane3.setViewportView(txtobs);

        cmddeletar.setText("Del");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Cadastro Automovel");
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameOpened(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel5.setText("Preço");

        jLabel8.setText("Obs");

        jLabel9.setText("Modelo");

        txtidautomovel1.setEnabled(false);
        txtidautomovel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidautomovel1ActionPerformed(evt);
            }
        });

        txtpreco1.setEnabled(false);

        cmbmodelo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um perfil", "BMW", "MERCEDES", "TOYOTA", "ACURA", "HONDA", "SUZUKI" }));
        cmbmodelo1.setEnabled(false);

        cmdprimero1.setText("<<");
        cmdprimero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimero1ActionPerformed(evt);
            }
        });

        cmdanterior1.setText("<");
        cmdanterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanterior1ActionPerformed(evt);
            }
        });

        cmdseguinte1.setText(">");
        cmdseguinte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdseguinte1ActionPerformed(evt);
            }
        });

        cmdultimo1.setText(">>");
        cmdultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimo1ActionPerformed(evt);
            }
        });

        cmdnovo1.setText("Add");
        cmdnovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovo1ActionPerformed(evt);
            }
        });

        cmdeditar1.setText("Edt");
        cmdeditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditar1ActionPerformed(evt);
            }
        });

        cmdsalvar1.setText("Gdr");
        cmdsalvar1.setEnabled(false);
        cmdsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvar1ActionPerformed(evt);
            }
        });

        cmdcancelar1.setText("cls");
        cmdcancelar1.setEnabled(false);
        cmdcancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelar1ActionPerformed(evt);
            }
        });

        cmdpesqusar1.setText("psq");
        cmdpesqusar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesqusar1ActionPerformed(evt);
            }
        });

        Ctable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Ctable1);

        txtobs1.setColumns(20);
        txtobs1.setRows(5);
        jScrollPane4.setViewportView(txtobs1);

        cmddeletar1.setText("Del");
        cmddeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(txtidautomovel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cmbmodelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmdprimero1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdanterior1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdseguinte1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdultimo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdnovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdeditar1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdcancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdsalvar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmddeletar1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdpesqusar1)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtidautomovel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmodelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtpreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdprimero1)
                    .addComponent(cmdanterior1)
                    .addComponent(cmdseguinte1)
                    .addComponent(cmdultimo1)
                    .addComponent(cmdnovo1)
                    .addComponent(cmdeditar1)
                    .addComponent(cmdsalvar1)
                    .addComponent(cmdcancelar1)
                    .addComponent(cmdpesqusar1)
                    .addComponent(cmddeletar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(txtidautomovel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cmbmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmdprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdseguinte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdultimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdeditar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(cmddeletar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdpesqusar)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtidautomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdprimero)
                    .addComponent(cmdanterior)
                    .addComponent(cmdseguinte)
                    .addComponent(cmdultimo)
                    .addComponent(cmdnovo)
                    .addComponent(cmdeditar)
                    .addComponent(cmdsalvar)
                    .addComponent(cmdcancelar)
                    .addComponent(cmdpesqusar)
                    .addComponent(cmddeletar))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidautomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidautomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidautomovelActionPerformed

    private void cmdseguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdseguinteActionPerformed
        // TODO add your handling code here:
        automovelatual++;
        if (automovelatual == clsdados.NUsuario()) {
            automovelatual = 0;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdseguinteActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        if (txtidautomovel.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o ID");
            txtidautomovel.requestFocusInWindow();
            return;
        }
        if (cmbmodelo.getSelectedItem().equals(0)) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Modelo");
            cmbmodelo.requestFocusInWindow();
            return;
        }
        if (txtpreco.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o preço do Automovel");
            txtpreco.requestFocusInWindow();
            return;
        }
        if (txtobs.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Descreva o automovel");
            txtobs.requestFocusInWindow();
            return;
        }

        if (Utilidades.isNumeric(txtpreco.getText())) {
        } else {
            JOptionPane.showMessageDialog(rootPane, "So aceita valores numericos");
            txtpreco.requestFocusInWindow();
            return;
        }

        int preco = Integer.parseInt(txtpreco.getText());
        if (preco <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Não deve ser menor ou igual a 0");
            txtpreco.requestFocusInWindow();
            return;
        }

        int poslinha = clsdados.LinhaAutomovel(Integer.parseInt(txtidautomovel.getText()));
        if (cmdNovo) {
            if (poslinha != -1) {
                JOptionPane.showMessageDialog(rootPane, "Já existe este automovel");
                txtidautomovel.requestFocusInWindow();
                return;
            }
        } else if (poslinha == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não existe este Automovel");
            txtidautomovel.requestFocusInWindow();
            return;
        }

        Automovel MAutomovel = new Automovel(Integer.parseInt(txtidautomovel.getText()),(String)cmbmodelo.getSelectedItem(), preco, txtobs.getText());

        String msg;
        if (cmdNovo) {
            msg = clsdados.CadAutomovel(MAutomovel);
        } else {
            msg = clsdados.EditarAutomovel(MAutomovel, poslinha);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        // guardar:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidautomovel.setEnabled(false);
        txtpreco.setEnabled(false);
        txtobs.setEnabled(false);
        cmbmodelo.setEnabled(false);

        CarregarTable();
    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovoActionPerformed
        // Adicionar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        txtidautomovel.setEnabled(true);
        txtpreco.setEnabled(true);
        txtobs.setEnabled(true);
        cmbmodelo.setEnabled(true);

        txtidautomovel.setText("");
        txtpreco.setText("");
        txtobs.setText("");
        cmbmodelo.setSelectedIndex(0);

        cmdNovo = true;

        txtidautomovel.requestFocusInWindow();

        CarregarTable();

    }//GEN-LAST:event_cmdnovoActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // editar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        txtpreco.setEnabled(true);
        txtobs.setEnabled(true);
        cmbmodelo.setEnabled(true);

        cmdNovo = false;

        txtpreco.requestFocusInWindow();
    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidautomovel.setEnabled(false);
        txtpreco.setEnabled(false);
        txtobs.setEnabled(false);
        cmbmodelo.setEnabled(false);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        visulisarCadastro();
        CarregarTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeroActionPerformed
        // TODO add your handling code here:
        automovelatual = 0;
        visulisarCadastro();
    }//GEN-LAST:event_cmdprimeroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        // TODO add your handling code here:

        automovelatual = clsdados.NAutomovel() - 1;
        visulisarCadastro();
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        // TODO add your handling code here:
        automovelatual--;
        if (automovelatual == -1) {
            automovelatual = clsdados.NAutomovel() - 1;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmdpesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesqusarActionPerformed
        // TODO add your handling code here:

        String automovel = JOptionPane.showInputDialog("Digite o ID para realisar a pesquisa");
        if (automovel.equals("")) {
            return;
        }
        int posL = clsdados.LinhaAutomovel(Integer.parseInt(automovel));
        if (posL == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não foi encontrado");
            return;
        }
        automovelatual = posL;
        visulisarCadastro();
    }//GEN-LAST:event_cmdpesqusarActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        // TODO add your handling code here:
        int Del = JOptionPane.showConfirmDialog(rootPane, "Quer mesmo deletar ?");
        if(Del !=0){
            return;
        }
        String msg;
        msg = clsdados.DeletarAutomovel(automovelatual);
        JOptionPane.showMessageDialog(rootPane, msg);
        automovelatual = 0;
        visulisarCadastro();
        CarregarTable();

    }//GEN-LAST:event_cmddeletarActionPerformed

    private void txtidautomovel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidautomovel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidautomovel1ActionPerformed

    private void cmdprimero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdprimero1ActionPerformed

    private void cmdanterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanterior1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdanterior1ActionPerformed

    private void cmdseguinte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdseguinte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdseguinte1ActionPerformed

    private void cmdultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdultimo1ActionPerformed

    private void cmdnovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdnovo1ActionPerformed

    private void cmdeditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdeditar1ActionPerformed

    private void cmdsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdsalvar1ActionPerformed

    private void cmdcancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdcancelar1ActionPerformed

    private void cmdpesqusar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesqusar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdpesqusar1ActionPerformed

    private void cmddeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmddeletar1ActionPerformed

    private void jInternalFrame1formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formInternalFrameOpened

    private void CtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CtableMouseClicked
//        // 
//         int selecionado = this.Ctable.getSelectedRow();
//       String id = this.Ctable.getValueAt(selecionado, 0).toString();
//       String modelo = this.Ctable.getValueAt(selecionado, 1).toString();
//       txtid.setText(id);
//       txtmodelo.setText(modelo);
    }//GEN-LAST:event_CtableMouseClicked
    private void visulisarCadastro() {
        txtidautomovel.setText("" + clsdados.getAutomovel()[automovelatual].getIdautomovel());
        txtpreco.setText("" + clsdados.getAutomovel()[automovelatual].getPreco());
        txtobs.setText(clsdados.getAutomovel()[automovelatual].getObservacao());
        cmbmodelo.setSelectedItem(clsdados.getAutomovel()[automovelatual].getModelo());
    }

    private void CarregarTable() {
        String titulocabesalho[] = {"ID", "MODELO", "PREÇO", "OBS"};
        String RegCadastro[] = new String[4];
        Usertabe = new DefaultTableModel(null, titulocabesalho);
        for (int i = 0; i < clsdados.NAutomovel(); i++) {
            RegCadastro[0] = "" +clsdados.getAutomovel()[i].getIdautomovel();
            RegCadastro[1] = (clsdados.getAutomovel()[i].getModelo());
            RegCadastro[2] = "" + clsdados.getAutomovel()[i].getPreco();
            RegCadastro[3] = clsdados.getAutomovel()[i].getObservacao();

            Usertabe.addRow(RegCadastro);

        }
        Ctable.setModel(Usertabe);
        
    }
        private String Modelo (int modelo){
            switch(modelo){
                case 1:
                    return "BMW";
                case 2:
                    return "MERCEDES";
                case 3:
                    return "TOYOTA";
                case 4:
                    return "ACURA";
                case 5:
                    return "ONDA";
                case 6:
                    return "SUZUKI";
                default:
                    return "";
            }
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ctable;
    private javax.swing.JTable Ctable1;
    private javax.swing.JComboBox<String> cmbmodelo;
    private javax.swing.JComboBox<String> cmbmodelo1;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdanterior1;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmdcancelar1;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmddeletar1;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdeditar1;
    private javax.swing.JButton cmdnovo;
    private javax.swing.JButton cmdnovo1;
    private javax.swing.JButton cmdpesqusar;
    private javax.swing.JButton cmdpesqusar1;
    private javax.swing.JButton cmdprimero;
    private javax.swing.JButton cmdprimero1;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdsalvar1;
    private javax.swing.JButton cmdseguinte;
    private javax.swing.JButton cmdseguinte1;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JButton cmdultimo1;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtidautomovel;
    private javax.swing.JTextField txtidautomovel1;
    private javax.swing.JTextArea txtobs;
    private javax.swing.JTextArea txtobs1;
    private javax.swing.JTextField txtpreco;
    private javax.swing.JTextField txtpreco1;
    // End of variables declaration//GEN-END:variables
}
