/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Cliente;
import classes.Dados;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gelson Tavares
 */
public class frmClientes extends javax.swing.JInternalFrame {

    private Dados clsdados;
    private int clienteatual = 0;
    private boolean cmdNovo = false;
    private DefaultTableModel Usertabe;

    public void setDados(Dados clsdados) {
        this.clsdados = clsdados;
    }

    public frmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        cmbindetifica = new javax.swing.JComboBox<>();
        cmdprimero = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdseguinte = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdnovo = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdpesqusar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ctable = new javax.swing.JTable();
        cmddeletar = new javax.swing.JButton();
        txtsobnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbbairo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        canlcvenda = new com.toedter.calendar.JDateChooser();
        canlcnasc = new com.toedter.calendar.JDateChooser();

        jLabel7.setText("jLabel7");

        jTextField2.setText("jTextField2");

        jButton5.setText("jButton5");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro  Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        jLabel3.setText("Sob Nome");

        jLabel6.setText("Indentificação");

        txtidcliente.setEnabled(false);
        txtidcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidclienteActionPerformed(evt);
            }
        });

        txtnome.setEnabled(false);

        cmbindetifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Identificação", "BILHETE DE IDENTIDADE", "PASSAPORTEl", " " }));
        cmbindetifica.setEnabled(false);

        cmdprimero.setText("<<");
        cmdprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeroActionPerformed(evt);
            }
        });

        cmdanterior.setText("<");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdseguinte.setText(">");
        cmdseguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdseguinteActionPerformed(evt);
            }
        });

        cmdultimo.setText(">>");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdnovo.setText("Add");
        cmdnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovoActionPerformed(evt);
            }
        });

        cmdeditar.setText("Edt");
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });

        cmdsalvar.setText("Gdr");
        cmdsalvar.setEnabled(false);
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdcancelar.setText("cls");
        cmdcancelar.setEnabled(false);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdpesqusar.setText("psq");
        cmdpesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesqusarActionPerformed(evt);
            }
        });

        Ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Ctable);

        cmddeletar.setText("Del");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        txtsobnome.setEnabled(false);

        jLabel5.setText("Endereço");

        txtendereco.setEnabled(false);

        jLabel8.setText("Telefone");

        txttelefone.setEnabled(false);

        jLabel10.setText("Bairo");

        cmbbairo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Bairo", "MISQUITA", "ÁGUA BOBO", "PALHA", "VILA MARIA", "RUA 3 DE FEVEREIRO", "ILHÉU S. AMARO", "SANTANA" }));
        cmbbairo.setEnabled(false);
        cmbbairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbairoActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        txtemail.setEnabled(false);

        jLabel4.setText("Data Nasc:");

        jLabel9.setText("Data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtendereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsobnome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbindetifica, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addComponent(canlcvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(canlcnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbbairo, 0, 217, Short.MAX_VALUE))
                                    .addComponent(txtemail))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cmdprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdanterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdseguinte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdultimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdeditar)
                .addGap(18, 18, 18)
                .addComponent(cmdcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdpesqusar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbindetifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(canlcvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsobnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cmbbairo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(canlcnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdprimero)
                    .addComponent(cmdanterior)
                    .addComponent(cmdseguinte)
                    .addComponent(cmdultimo)
                    .addComponent(cmdnovo)
                    .addComponent(cmdeditar)
                    .addComponent(cmdsalvar)
                    .addComponent(cmdcancelar)
                    .addComponent(cmdpesqusar)
                    .addComponent(cmddeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteActionPerformed

    private void cmdseguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdseguinteActionPerformed
        // TODO add your handling code here:
        clienteatual++;
        if (clienteatual == clsdados.NUsuario()) {
            clienteatual = 0;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdseguinteActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        if (txtidcliente.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o ID");
            txtidcliente.requestFocusInWindow();
            return;
        }
        if (cmbindetifica.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione a tua identificação");
            cmbindetifica.requestFocusInWindow();
            return;
        }
        if (cmbbairo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione o teu bairo");
            cmbbairo.requestFocusInWindow();
            return;
        }
        if (txtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o teu nome");
            txtnome.requestFocusInWindow();
            return;
        }
        if (txtsobnome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o teu sobre nome");
            txtsobnome.requestFocusInWindow();
            return;
        }
        if (txtendereco.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o teu endereso");
            txtendereco.requestFocusInWindow();
            return;
        }
        if (txttelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Deiche o seu número de TELEFONE");
            txttelefone.requestFocusInWindow();
            return;
        }
        if (txtemail.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Deiche o seu coreio Eletronico (Email)");
            txtemail.requestFocusInWindow();
            return;
        }
       
       

        int poslinha = clsdados.LinhaUsuario(txtidcliente.getText());
        if (cmdNovo) {
            if (poslinha != -1) {
                JOptionPane.showMessageDialog(rootPane, "Já existe este cadastro");
                txtidcliente.requestFocusInWindow();
                return;
            }
        } else if (poslinha == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não existe este cadastro");
            txtidcliente.requestFocusInWindow();
            return;
        }

        
        Cliente MCliente = new Cliente(Integer.parseInt(txtidcliente.getText()), cmbindetifica.getSelectedIndex(), txtnome.getText(), 
                txtsobnome.getText(), txtendereco.getText(), 
                txttelefone.getText(), cmbbairo.getSelectedIndex(), canlcvenda.getDate(), canlcnasc.getDate(), txtemail.getText());
        String msg;
        if (cmdNovo) {
            msg = clsdados.CadCliente(MCliente);
        } else {
            msg = clsdados.EditarCliente(MCliente, poslinha);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        // guardar:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidcliente.setEnabled(false);
        cmbindetifica.setEnabled(false);
        txtnome.setEnabled(false);
        txtsobnome.setEnabled(false);
        txtendereco.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefone.setEnabled(false);
        txtemail.setEnabled(false);
        cmbbairo.setEnabled(false);
        canlcvenda.setEnabled(true);
        canlcnasc.setEnabled(false);

        CarregarTable();
    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovoActionPerformed
        // Adicionar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        txtidcliente.setEnabled(true);
        cmbindetifica.setEnabled(true);
        txtnome.setEnabled(true);
        txtsobnome.setEnabled(true);
        txtendereco.setEnabled(true);
        txtemail.setEnabled(true);
        txttelefone.setEnabled(true);
        txtemail.setEnabled(true);
        cmbbairo.setEnabled(true);
        canlcvenda.setEnabled(true);
        canlcnasc.setEnabled(true);

        txtidcliente.setText("");
        cmbindetifica.setSelectedIndex(0);
        txtnome.setText("");
        txtsobnome.setText("");
        txttelefone.setText("");
        txtendereco.setText("");
        cmbbairo.setSelectedIndex(0);
        canlcvenda.setDate(new Date());
        canlcnasc.setDate(new Date());
        txtemail.setText("");

        cmdNovo = true;

        txtidcliente.requestFocusInWindow();

        CarregarTable();

    }//GEN-LAST:event_cmdnovoActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // editar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        cmbindetifica.setEnabled(true);
        txtnome.setEnabled(true);
        txtsobnome.setEnabled(true);
        txtendereco.setEnabled(true);
        txtemail.setEnabled(true);
        txttelefone.setEnabled(true);
        cmbbairo.setEnabled(true);
        canlcvenda.setEnabled(true);
        canlcnasc.setEnabled(true);
        txtemail.setEnabled(true);

        cmdNovo = false;

        txtnome.requestFocusInWindow();
    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidcliente.setEnabled(false);
        cmbindetifica.setEnabled(false);
        txtnome.setEnabled(false);
        txtsobnome.setEnabled(false);
        txtendereco.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefone.setEnabled(false);
        cmbbairo.setEnabled(false);
        canlcvenda.setEnabled(false);
        canlcnasc.setEnabled(false);
        txtemail.setEnabled(false);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        visulisarCadastro();
        CarregarTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeroActionPerformed
        // TODO add your handling code here:
        clienteatual = 0;
        visulisarCadastro();
    }//GEN-LAST:event_cmdprimeroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        // TODO add your handling code here:

        clienteatual = clsdados.NCliente() - 1;
        visulisarCadastro();
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        // TODO add your handling code here:
        clienteatual--;
        if (clienteatual == -1) {
            clienteatual = clsdados.NCliente() - 1;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmdpesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesqusarActionPerformed
        // TODO add your handling code here:

        String cliente = JOptionPane.showInputDialog("Digite o ID para efetuar a pesquisa");
        if (cliente.equals("")) {
            return;
        }
        int posL = clsdados.LinhaCliente(Integer.parseInt(cliente));
        if (posL == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não foi encontrado o cadastro de cliente que procuras");
            return;
        }
        clienteatual = posL;
        visulisarCadastro();
    }//GEN-LAST:event_cmdpesqusarActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        // TODO add your handling code here:
        int Del = JOptionPane.showConfirmDialog(rootPane, "Quer mesmo deletar");
        if (Del != 0) {
            return;
        }
        String msg;
        msg = clsdados.DeletarCliente(clienteatual);
        JOptionPane.showMessageDialog(rootPane, msg);
        clienteatual = 0;
        visulisarCadastro();
        CarregarTable();

    }//GEN-LAST:event_cmddeletarActionPerformed

    private void cmbbairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbairoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbairoActionPerformed
    private void visulisarCadastro() {
        txtidcliente.setText("" +clsdados.getCliente()[clienteatual].getIdcliente());
        txtnome.setText("" + clsdados.getCliente()[clienteatual].getNome());
        txtsobnome.setText(clsdados.getCliente()[clienteatual].getSobnome());
        txttelefone.setText(clsdados.getCliente()[clienteatual].getTelefone());
        txtendereco.setText(clsdados.getCliente()[clienteatual].getEndereco());
        txtemail.setText(clsdados.getCliente()[clienteatual].getEmail());
        cmbindetifica.setSelectedItem(clsdados.getCliente()[clienteatual].getIdentificacao());
        cmbbairo.setSelectedItem(clsdados.getCliente()[clienteatual].getBairo());
        canlcvenda.setDate(clsdados.getCliente()[clienteatual].getDatavenda());
        canlcnasc.setDate(clsdados.getCliente()[clienteatual].getDatanascimento());
    }

    private void CarregarTable() {
        String titulocabesalho[] = {"ID", "NOME", "SOBRENOME", "IDENTF", "BAIRO", "DATA", "D-NASC"};
        String RegCadastro[] = new String[7];
        Usertabe = new DefaultTableModel(null, titulocabesalho);
        for (int i = 0; i < clsdados.NCliente(); i++) {
            RegCadastro[0] = "" + clsdados.getCliente()[i].getIdcliente();
            RegCadastro[1] = clsdados.getCliente()[i].getNome();
            RegCadastro[2] = clsdados.getCliente()[i].getSobnome();
            RegCadastro[3] = Id(clsdados.getCliente()[i].getIdentificacao());
            RegCadastro[4] = Bairo(clsdados.getCliente()[i].getBairo());
            RegCadastro[5] = "" + clsdados.getCliente()[i].getDatavenda();
            RegCadastro[6] = "" + clsdados.getCliente()[i].getDatanascimento();

            Usertabe.addRow(RegCadastro);

        }
        Ctable.setModel(Usertabe);
    }

    private String Id(int indc) {
        switch (indc) {
            case 0:
                return "BILHETE DE IDENTIDADE";

            case 1:
                return "PASSAPORTE";
            default:
                return "SEM IDENTIFICAÇÃO";
        }
    }

    private String Bairo(int bairo) {
        switch (bairo) {
            case 1:
                return "MISQUITA";
            case 2:
                return "ÁGUA BÔBÔ";
            case 3:
                return "PALHA";
            case 4:
                return "VILA MARIA";
            case 5:
                return "RUA 3 DE FEVEREIRO";
            case 6:
                return "ILHÉU S. AMARO";
            case 7:
                return "SANTANA";
            default:
                return "CIDADE CAPITAL";
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ctable;
    private com.toedter.calendar.JDateChooser canlcnasc;
    private com.toedter.calendar.JDateChooser canlcvenda;
    private javax.swing.JComboBox<String> cmbbairo;
    private javax.swing.JComboBox<String> cmbindetifica;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdnovo;
    private javax.swing.JButton cmdpesqusar;
    private javax.swing.JButton cmdprimero;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdseguinte;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsobnome;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
