/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Dados;

/**
 *
 * @author Gelson Tavares
 */
public class frmMenu extends javax.swing.JFrame {
private Dados clsdados;
private int perfil;
    
   public void setDados(Dados clsdados){
       this.clsdados = clsdados;
   }
   public void setupPerfil(int perfil){
       this.perfil = perfil;
   }
    public frmMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deskpanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menoarq = new javax.swing.JMenu();
        menoarqusario = new javax.swing.JMenuItem();
        menoarqcliente = new javax.swing.JMenuItem();
        menoarqautomovel = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menoarqaltusuario = new javax.swing.JMenuItem();
        menoarqaltsenha = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menoarqsair = new javax.swing.JMenuItem();
        menomov = new javax.swing.JMenu();
        menomovvenda = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menomovrelvenda = new javax.swing.JMenuItem();
        menomovrelaluguer = new javax.swing.JMenuItem();
        menoajud = new javax.swing.JMenu();
        menoajudajuda = new javax.swing.JMenuItem();
        menoajudsobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Systema Stand");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Deskpanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout DeskpanelLayout = new javax.swing.GroupLayout(Deskpanel);
        Deskpanel.setLayout(DeskpanelLayout);
        DeskpanelLayout.setHorizontalGroup(
            DeskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        DeskpanelLayout.setVerticalGroup(
            DeskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        menoarq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/arquivo.png"))); // NOI18N
        menoarq.setText("Arquivos");

        menoarqusario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuario.png"))); // NOI18N
        menoarqusario.setText("Cad Usuario");
        menoarqusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqusarioActionPerformed(evt);
            }
        });
        menoarq.add(menoarqusario);

        menoarqcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cliente.png"))); // NOI18N
        menoarqcliente.setText("Cad Cliente");
        menoarqcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqclienteActionPerformed(evt);
            }
        });
        menoarq.add(menoarqcliente);

        menoarqautomovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Cabriolet_Red_icon-icons.com_54906.png"))); // NOI18N
        menoarqautomovel.setText("Cad Automovel");
        menoarqautomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqautomovelActionPerformed(evt);
            }
        });
        menoarq.add(menoarqautomovel);
        menoarq.add(jSeparator1);

        menoarqaltusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/adicionar-usuario.png"))); // NOI18N
        menoarqaltusuario.setText("Alterar Usuario");
        menoarqaltusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqaltusuarioActionPerformed(evt);
            }
        });
        menoarq.add(menoarqaltusuario);

        menoarqaltsenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/venda-a.png"))); // NOI18N
        menoarqaltsenha.setText("Alterar Senha");
        menoarqaltsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqaltsenhaActionPerformed(evt);
            }
        });
        menoarq.add(menoarqaltsenha);
        menoarq.add(jSeparator2);

        menoarqsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/sair.png"))); // NOI18N
        menoarqsair.setText("Sair");
        menoarqsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoarqsairActionPerformed(evt);
            }
        });
        menoarq.add(menoarqsair);

        jMenuBar1.add(menoarq);

        menomov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/movimento.png"))); // NOI18N
        menomov.setText("Movimento");

        menomovvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Cabriolet_Red_icon-icons.com_54906.png"))); // NOI18N
        menomovvenda.setText("Venda");
        menomovvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menomovvendaActionPerformed(evt);
            }
        });
        menomov.add(menomovvenda);
        menomov.add(jSeparator3);

        menomovrelvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/documento.png"))); // NOI18N
        menomovrelvenda.setText("Relatorio de Venda");
        menomov.add(menomovrelvenda);

        menomovrelaluguer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/relatorio.png"))); // NOI18N
        menomovrelaluguer.setText("Relatorio de Aluguer");
        menomov.add(menomovrelaluguer);

        jMenuBar1.add(menomov);

        menoajud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Help_icon-icons.com_73700.png"))); // NOI18N
        menoajud.setText("Ajuda");

        menoajudajuda.setText("Ajuda");
        menoajudajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoajudajudaActionPerformed(evt);
            }
        });
        menoajud.add(menoajudajuda);

        menoajudsobre.setText("Sobre");
        menoajudsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoajudsobreActionPerformed(evt);
            }
        });
        menoajud.add(menoajudsobre);

        jMenuBar1.add(menoajud);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menoarqusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqusarioActionPerformed
        // chamando a Tela de Usuario:
        frmUsuario frmusuario = new frmUsuario();
        frmusuario.setDados(clsdados);
        Deskpanel.add(frmusuario);
        frmusuario.show();
    }//GEN-LAST:event_menoarqusarioActionPerformed

    private void menoarqautomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqautomovelActionPerformed
        // chamando a Tela de Automovel:
        frmAutomovel frmauto = new frmAutomovel();
        frmauto.setDados(clsdados);
        Deskpanel.add(frmauto);
        frmauto.show();
        
    }//GEN-LAST:event_menoarqautomovelActionPerformed

    private void menoarqclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqclienteActionPerformed
        // chamando a Tela de cliente:
        frmClientes clientes = new frmClientes();
        clientes.setDados(clsdados);
        Deskpanel.add(clientes);
        clientes.show();
    }//GEN-LAST:event_menoarqclienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /* controle de acesso: 2 = funcionario 1= gerente, 2 não tera
        acesso a determinadas partes do programa
        */
        
        if(perfil == 2){
            menoarqusario.setEnabled(false);
            menoarqautomovel.setEnabled(false);
            menoarqcliente.setEnabled(false);
            menomovrelvenda.setEnabled(false);
            menomovrelaluguer.setEnabled(false);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void menomovvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menomovvendaActionPerformed
      // chamando a Tela de venda:
        frmVenda venda = new frmVenda();
       venda.setDados(clsdados);
       Deskpanel.add(venda);
       venda.show();
    }//GEN-LAST:event_menomovvendaActionPerformed

    private void menoajudsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoajudsobreActionPerformed
        // chamando a Tela de sobre:
        Sobre s = new Sobre(this, rootPaneCheckingEnabled);
      s.setLocationRelativeTo(this);
      s.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_menoajudsobreActionPerformed

    private void menoarqsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqsairActionPerformed
        //sair do menu principal e guar dado no banco de dados; 
        clsdados.CadastroGeral();
        System.exit(0);
    }//GEN-LAST:event_menoarqsairActionPerformed

    private void menoajudajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoajudajudaActionPerformed
        // chamando a Tela de ajuda:
        Ajuda a = new Ajuda(this, rootPaneCheckingEnabled);
        a.setLocationRelativeTo(this);
        a.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_menoajudajudaActionPerformed

    private void menoarqaltusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqaltusuarioActionPerformed
        // 
        frmUsuario usuari = new frmUsuario();
        usuari.setDados(clsdados);
        Deskpanel.add(usuari);
        usuari.show();
    }//GEN-LAST:event_menoarqaltusuarioActionPerformed

    private void menoarqaltsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoarqaltsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoarqaltsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Deskpanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menoajud;
    private javax.swing.JMenuItem menoajudajuda;
    private javax.swing.JMenuItem menoajudsobre;
    private javax.swing.JMenu menoarq;
    private javax.swing.JMenuItem menoarqaltsenha;
    private javax.swing.JMenuItem menoarqaltusuario;
    private javax.swing.JMenuItem menoarqautomovel;
    private javax.swing.JMenuItem menoarqcliente;
    private javax.swing.JMenuItem menoarqsair;
    private javax.swing.JMenuItem menoarqusario;
    private javax.swing.JMenu menomov;
    private javax.swing.JMenuItem menomovrelaluguer;
    private javax.swing.JMenuItem menomovrelvenda;
    private javax.swing.JMenuItem menomovvenda;
    // End of variables declaration//GEN-END:variables
}
