/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Dados;
import classes.Usuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gelson Tavares
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    private Dados clsdados;
    private int usuarioatual = 0;
    private boolean cmdNovo = false;
    private DefaultTableModel Usertabe;

    public void setDados(Dados clsdados) {
        this.clsdados = clsdados;
    }

    public frmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidusuario = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtsobnome = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        txtconfsenha = new javax.swing.JPasswordField();
        cmbperfil = new javax.swing.JComboBox<>();
        cmdprimero = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdseguinte = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdnovo = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdpesqusar = new javax.swing.JButton();
        cmddeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ctable = new javax.swing.JTable();

        jLabel7.setText("jLabel7");

        jTextField2.setText("jTextField2");

        jButton5.setText("jButton5");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        jLabel3.setText("Sbrenome");

        jLabel4.setText("Senha");

        jLabel5.setText("Conf Senha");

        jLabel6.setText("Perfil");

        txtidusuario.setEnabled(false);
        txtidusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidusuarioActionPerformed(evt);
            }
        });

        txtnome.setEnabled(false);

        txtsobnome.setEnabled(false);
        txtsobnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsobnomeActionPerformed(evt);
            }
        });

        txtsenha.setEnabled(false);

        txtconfsenha.setEnabled(false);
        txtconfsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfsenhaActionPerformed(evt);
            }
        });

        cmbperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um perfil", "GERENTE", "FUNCIONARIO" }));
        cmbperfil.setEnabled(false);

        cmdprimero.setText("<<");
        cmdprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeroActionPerformed(evt);
            }
        });

        cmdanterior.setText("<");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdseguinte.setText(">");
        cmdseguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdseguinteActionPerformed(evt);
            }
        });

        cmdultimo.setText(">>");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdnovo.setText("Add");
        cmdnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovoActionPerformed(evt);
            }
        });

        cmdeditar.setText("Edt");
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });

        cmdsalvar.setText("Gdr");
        cmdsalvar.setEnabled(false);
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdcancelar.setText("cls");
        cmdcancelar.setEnabled(false);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        cmdpesqusar.setText("psq");
        cmdpesqusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesqusarActionPerformed(evt);
            }
        });

        cmddeletar.setText("Del");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        Ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Ctable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdanterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdseguinte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdultimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdeditar)
                        .addGap(4, 4, 4)
                        .addComponent(cmdcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdpesqusar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtsobnome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(cmbperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsobnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdprimero)
                    .addComponent(cmdanterior)
                    .addComponent(cmdseguinte)
                    .addComponent(cmdultimo)
                    .addComponent(cmdnovo)
                    .addComponent(cmdeditar)
                    .addComponent(cmdsalvar)
                    .addComponent(cmdcancelar)
                    .addComponent(cmdpesqusar)
                    .addComponent(cmddeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsobnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsobnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsobnomeActionPerformed

    private void txtidusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidusuarioActionPerformed

    private void txtconfsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfsenhaActionPerformed

    private void cmdseguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdseguinteActionPerformed
        // TODO add your handling code here:
        usuarioatual++;
        if (usuarioatual == clsdados.NUsuario()) {
            usuarioatual = 0;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdseguinteActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed

        if (txtidusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite o ID");
            txtidusuario.requestFocusInWindow();
            return;
        }
        if (cmbperfil.getSelectedItem().equals(0)) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um perfil");
            cmbperfil.requestFocusInWindow();
            return;
        }
        if (txtnome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite seu nome");
            txtnome.requestFocusInWindow();
            return;
        }
        if (txtsobnome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite seu sobre - nome");
            txtsobnome.requestFocusInWindow();
            return;
        }
        String SSenha = new String(txtsenha.getPassword());
        String ConfSenha = new String(txtconfsenha.getPassword());

        if (SSenha.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite a sua senha");
            txtsenha.requestFocusInWindow();
            return;
        }
        if (ConfSenha.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite a confirmação de senha");
            txtconfsenha.requestFocusInWindow();
            return;
        }

        if (!SSenha.equals(ConfSenha)) {
            JOptionPane.showMessageDialog(rootPane, "Por favor confirma a senha");
            txtconfsenha.requestFocusInWindow();
            return;
        }

        int poslinha = clsdados.LinhaUsuario(txtidusuario.getText());
        if (cmdNovo) {
            if (poslinha != -1) {
                JOptionPane.showMessageDialog(rootPane, "Já existe este cadastro de usuario");
                txtidusuario.requestFocusInWindow();
                return;
            }
        }

        Usuarios MUsuario = new Usuarios(txtidusuario.getText(), txtnome.getText(), txtsobnome.getText(), SSenha,cmbperfil.getSelectedIndex());
        String msg;
        if (cmdNovo) {
            msg = clsdados.CadUsuario(MUsuario);
        } else {
            msg = clsdados.EditarUsuario(MUsuario, poslinha);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        // guardar:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidusuario.setEnabled(false);
        txtnome.setEnabled(false);
        txtsobnome.setEnabled(false);
        txtsenha.setEnabled(false);
        txtconfsenha.setEnabled(false);
        cmbperfil.setEnabled(false);

        CarregarTable();
    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmdnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovoActionPerformed
        // Adicionar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        txtidusuario.setEnabled(true);
        txtnome.setEnabled(true);
        txtsobnome.setEnabled(true);
        txtsenha.setEnabled(true);
        txtconfsenha.setEnabled(true);
        cmbperfil.setEnabled(true);

        txtidusuario.setText("");
        txtnome.setText("");
        txtsobnome.setText("");
        txtsenha.setText("");
        txtconfsenha.setText("");
        cmbperfil.setSelectedIndex(0);

        cmdNovo = true;

        txtidusuario.requestFocusInWindow();

        CarregarTable();

    }//GEN-LAST:event_cmdnovoActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // editar:
        cmdprimero.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdseguinte.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdcancelar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmdeditar.setEnabled(false);
        cmdpesqusar.setEnabled(false);

        txtnome.setEnabled(true);
        txtsobnome.setEnabled(true);
        txtsenha.setEnabled(true);
        txtconfsenha.setEnabled(true);
        cmbperfil.setEnabled(true);

        cmdNovo = false;

        txtnome.requestFocusInWindow();
    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
        cmdprimero.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdseguinte.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdcancelar.setEnabled(false);
        cmddeletar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmdeditar.setEnabled(true);
        cmdpesqusar.setEnabled(true);

        txtidusuario.setEnabled(false);
        txtnome.setEnabled(false);
        txtsobnome.setEnabled(false);
        txtsenha.setEnabled(false);
        txtconfsenha.setEnabled(false);
        cmbperfil.setEnabled(false);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        visulisarCadastro();
        CarregarTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeroActionPerformed
        // TODO add your handling code here:
        usuarioatual = 0;
        visulisarCadastro();
    }//GEN-LAST:event_cmdprimeroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        // TODO add your handling code here:

        usuarioatual = clsdados.NUsuario() - 1;
        visulisarCadastro();
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        // TODO add your handling code here:
        usuarioatual--;
        if (usuarioatual == -1) {
            usuarioatual = clsdados.NUsuario() - 1;
        }
        visulisarCadastro();
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        // TODO add your handling code here:
        int Del = JOptionPane.showConfirmDialog(rootPane, "Quer mesmo deletar?");
        if (Del != 0) {
            return;
        }
        String msg = clsdados.DeletarUsuario(usuarioatual);
        JOptionPane.showMessageDialog(rootPane, msg);
        usuarioatual = 0;
        visulisarCadastro();
        CarregarTable();
    }//GEN-LAST:event_cmddeletarActionPerformed

    private void cmdpesqusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesqusarActionPerformed
        // TODO add your handling code here:

        String usuario = JOptionPane.showInputDialog("Digite o ID para efetuar a pesquisa");
        if (usuario.equals("")) {
            return;
        }
        int posL = clsdados.LinhaUsuario(usuario);
        if (posL == -1) {
            JOptionPane.showMessageDialog(rootPane, "Não foi encontrado");
            return;
        }
        usuarioatual = posL;
        visulisarCadastro();
    }//GEN-LAST:event_cmdpesqusarActionPerformed
    private void visulisarCadastro() {
        txtidusuario.setText(clsdados.getUsuarios()[usuarioatual].getIdusuario());
        txtnome.setText(clsdados.getUsuarios()[usuarioatual].getNome());
        txtsobnome.setText(clsdados.getUsuarios()[usuarioatual].getSobnome());
        txtsenha.setText(clsdados.getUsuarios()[usuarioatual].getSenha());
        txtconfsenha.setText(clsdados.getUsuarios()[usuarioatual].getSenha());
        cmbperfil.setSelectedItem(clsdados.getUsuarios()[usuarioatual].getPerfil());
    }

    private void CarregarTable() {
        String titulocabesalho[] = {"ID", "Nome", "Sob Nome", "Pelfil"};
        String RegCadastro[] = new String[4];
        Usertabe = new DefaultTableModel(null, titulocabesalho);
        for (int i = 0; i < clsdados.NUsuario(); i++) {
            RegCadastro[0] = clsdados.getUsuarios()[i].getIdusuario();
            RegCadastro[1] = clsdados.getUsuarios()[i].getNome();
            RegCadastro[2] = clsdados.getUsuarios()[i].getSobnome();
            RegCadastro[3] = Perfil(clsdados.getUsuarios()[i].getPerfil());

            Usertabe.addRow(RegCadastro);

        }
        Ctable.setModel(Usertabe);
    }

    private String Perfil(int perfil) {
        if (perfil == 1) {
            return "GERENTE";
        } else {

            return "FUNCIONARIO";
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ctable;
    private javax.swing.JComboBox<String> cmbperfil;
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdnovo;
    private javax.swing.JButton cmdpesqusar;
    private javax.swing.JButton cmdprimero;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdseguinte;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField txtconfsenha;
    private javax.swing.JTextField txtidusuario;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtsobnome;
    // End of variables declaration//GEN-END:variables
}
