/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Dados;
import classes.Servico;
import classes.Utilidades;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gelson Tavares
 */
public class frmVenda extends javax.swing.JInternalFrame {

    private Dados clsdados;
    private DefaultTableModel Usertabe;
    private int v = 1;
    private int m = 0;
    private double n = 0;
    private int t = 0;
    double total = 0;
    int totalqunt = 0;

    public void setDados(Dados clsdados) {
        this.clsdados = clsdados;
    }

    public frmVenda() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbcliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbautomovel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtquatidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvenda = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTotalquantidade = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Venda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("DATA");

        txtdata.setEnabled(false);

        jLabel2.setText("CLIENTE:");

        jLabel3.setText("AUTOMOVEL");

        cmbautomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbautomovelActionPerformed(evt);
            }
        });

        jLabel4.setText("QUANTIDADE");

        tblvenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblvenda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tblvendaMouseDragged(evt);
            }
        });
        tblvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblvendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblvenda);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CS");

        jButton3.setText("DEL");

        jButton4.setText("VENDER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL:");

        txtTotalquantidade.setEnabled(false);

        txtvalor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbautomovel, 0, 389, Short.MAX_VALUE))
                                    .addComponent(txtquatidade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cmbautomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Servico opcao = new Servico(0, "Cliente");
        cmbcliente.addItem(opcao);
        for (int i = 0; i < clsdados.NCliente(); i++) {
            opcao = new Servico(clsdados.getCliente()[i].getIdcliente(),
                    clsdados.getCliente()[i].getNome()
                    + "" + clsdados.getCliente()[i].getSobnome());
            cmbcliente.addItem(opcao);
        }

        opcao = new Servico(0, "Automovel");
        cmbautomovel.addItem(opcao);
        for (int i = 0; i < clsdados.NAutomovel(); i++) {
            opcao = new Servico(clsdados.getAutomovel()[i].getIdautomovel(),
                    clsdados.getAutomovel()[i].getModelo());

            cmbautomovel.addItem(opcao);
        }
        txtdata.setText(Utilidades.formatDate(new Date()));
        txtTotalquantidade.setText("0");
        txtvalor.setText("0");

        CarregarTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cmbautomovel.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Automovel");
            cmbautomovel.requestFocusInWindow();
            return;
        }

        if (txtquatidade.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Digite uma Quantidade");
            txtquatidade.requestFocusInWindow();
            return;
        }

        if (!Utilidades.isNumeric(txtquatidade.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Valor numerico");
            txtquatidade.requestFocusInWindow();
            return;
        }
        int quantidade = Integer.parseInt(txtquatidade.getText());
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Valor maior que zero (0)");
            txtquatidade.setText("");
            txtquatidade.requestFocusInWindow();
            return;
        }
        if (quantidade == 0) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Valor");
            txtquatidade.setText("");
            txtquatidade.requestFocusInWindow();
            return;
        }

        int pos = clsdados.LinhaAutomovel((int) ((Servico) cmbautomovel.getSelectedItem()).getValor());

        Servico c = new Servico(0, title);
        c.calcularPreco(quantidade, clsdados.getAutomovel()[pos].getPreco());

        String RegCadastro[] = new String[5];
        RegCadastro[0] = "" + clsdados.getAutomovel()[pos].getIdautomovel();
        RegCadastro[1] = clsdados.getAutomovel()[pos].getModelo();
        RegCadastro[2] = "" + clsdados.getAutomovel()[pos].getPreco();
        RegCadastro[3] = "" + quantidade;
        RegCadastro[4] = "" + c.getValor();

        Usertabe.addRow(RegCadastro);

        cmbautomovel.setSelectedIndex(0);
        txtquatidade.setText("");
        cmbautomovel.requestFocusInWindow();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.RIGHT);

        tblvenda.getColumnModel().getColumn(2).setCellRenderer(tabela);
        tblvenda.getColumnModel().getColumn(3).setCellRenderer(tabela);
        tblvenda.getColumnModel().getColumn(4).setCellRenderer(tabela);

        txtvalor.setText(Integer.toString(c.getAux()));
        double f = 0;

//        while (f<v) {
//           m+= Integer.parseInt(tblvenda.getValueAt(v, 3).toString());
//           n+= Double.parseDouble(tblvenda.getValueAt(v, 4).toString());
//           f++;
//        }
//        if(t!=0){
//          t++;
//        }
//     
//       v++;
        totalqunt += quantidade;
        txtTotalquantidade.setText("" + totalqunt);

        total += c.getValor();

        txtvalor.setText("" + total);

    }//GEN-LAST:event_jButton1ActionPerformed


    private void tblvendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblvendaMouseClicked


    }//GEN-LAST:event_tblvendaMouseClicked

    private void tblvendaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblvendaMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_tblvendaMouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cmbcliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente");
            cmbcliente.requestFocusInWindow();
            return;
        }

        if (cmbautomovel.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente");
            cmbautomovel.requestFocusInWindow();
            return;
        }

        int quantidade = Integer.parseInt(txtquatidade.getText());
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Valor maior que zero (0)");
            txtquatidade.setText("");
            txtquatidade.requestFocusInWindow();
            return;
        }
        if (quantidade == 0) {
            JOptionPane.showMessageDialog(rootPane, "Digite um Valor");
            txtquatidade.setText("");
            txtquatidade.requestFocusInWindow();
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbautomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbautomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbautomovelActionPerformed
    private void Totais() {
        int Numero = tblvenda.getRowCount();

        int somaquntidade = 0, somavalor = 0;

        for (int i = 0; i < Numero; i++) {
            somaquntidade += Utilidades.objectToInt(tblvenda.getValueAt(i, 3));
            somavalor += Utilidades.objectToInt(tblvenda.getValueAt(i, 4));

        }
        txtTotalquantidade.setText("" + somaquntidade);
        txtvalor.setText("" + somavalor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cmbautomovel;
    private javax.swing.JComboBox<Object> cmbcliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblvenda;
    private javax.swing.JTextField txtTotalquantidade;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtquatidade;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables

    private void CarregarTable() {
        String titulocabesalho[] = {"ID", "MARCA", "PREÇO", "QUNTIDADE", "VALOR"};
        String RegCadastro[] = new String[5];
        Usertabe = new DefaultTableModel(null, titulocabesalho);

        Usertabe.addRow(RegCadastro);

        tblvenda.setModel(Usertabe);

    }
}
